### ISSUE TITLE
Arduino UNO back to back TX/RX

### ISSUE THREAD

**Issue by MartinDavidWaller** [addibble/SoftwareSerial9#2]
Hi,

I'm trying to use your library to TX and RX 9 bit binary. As a test I have two Arduino UNO back to back with TX and RX on pins 2 and 3 with the wires twisted as you'd expect. On the transmit side I'm calling the write9() method and on the RX size I'm doing a simple read.

I'm finding that the data is one bit place out. If i transmit 0xCE, binary 1100 1110 then on the RX side I call read() and get 0x67, which in binary is 0110 0111 which is 1100 1110 shifted right one bit! All data seems to be suffering in this way.

I was wondering if you had seen this issue before?

Many thanks

Martin

**Comment by MartinDavidWaller** [comment]
Interestingly, if I tweak the main read loop in the recv method to read as given below then I get 0xCE as expected but I don't get data in the 9th bit when I've sent it? So if I call write9 with 0x100 then the read returns 0x00.

    // Read each of the 9 bits
    
    for (uint8_t i=9; i > 0; --i)
    {
	  if (rx_pin_read())
        d |= 0x80;

      if (i > 1)
      {
      	tunedDelay(_rx_delay_intrabit);
        d >>= 1;
      }
      
      DebugPulse(_DEBUG_PIN2, 1);
    }

**Comment by MartinDavidWaller** [comment]
It looks like the ONLY change you have to make to have this work is to replace the:

d |= 0x80;

with:

d |= 0x100;

This seems to work now. I'm now getting back the 9-bit data that I write out.

**Comment by addibble** [comment]
Hi, thanks for reporting this issue. I never used the receive functionality - only write. I also see that I had a pull request waiting from a year ago that also said it fixed this issue in a slightly different way. Can you check and see if it works for you?

**Comment by MartinDavidWaller** [comment]
Hi Andrew,

 

I’ll test it out again for you but it may be a few days as I’m back on another project at the moment.

 

I’ll let you know.

 

Martin
